"""hello

Revision ID: 3bc40b9497e7
Revises: 
Create Date: 2023-11-30 22:19:47.290764

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3bc40b9497e7'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Album',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('album_cover_path', sa.String(length=250), nullable=True),
    sa.Column('name', sa.String(length=30), nullable=False),
    sa.Column('artist_username', sa.String(length=50), nullable=False),
    sa.Column('artist_name', sa.String(length=50), nullable=False),
    sa.Column('year', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('album_cover_path'),
    sa.UniqueConstraint('name')
    )
    op.create_table('Playlist',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=30), nullable=False),
    sa.Column('user_username', sa.String(length=50), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_username', 'name')
    )
    op.create_table('User',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('username', sa.String(length=50), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('password', sa.String(length=120), nullable=False),
    sa.Column('role', sa.Integer(), nullable=False),
    sa.Column('status', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('username')
    )
    op.create_table('Song',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=30), nullable=False),
    sa.Column('artist_username', sa.String(length=50), nullable=False),
    sa.Column('artist_name', sa.String(length=50), nullable=False),
    sa.Column('album_id', sa.Integer(), nullable=True),
    sa.Column('genre', sa.String(length=50), nullable=False),
    sa.Column('year', sa.Integer(), nullable=False),
    sa.Column('audio_file_path', sa.String(length=250), nullable=False),
    sa.Column('cover_path', sa.String(length=250), nullable=False),
    sa.Column('duration', sa.Integer(), nullable=False),
    sa.Column('lyrics', sa.Text(), nullable=True),
    sa.Column('lyrics_rating', sa.Float(), nullable=False),
    sa.Column('lyrics_rating_count', sa.Integer(), nullable=False),
    sa.Column('total_lyrics_rating', sa.Float(), nullable=True),
    sa.Column('views', sa.Integer(), nullable=False),
    sa.Column('song_rating', sa.Float(), nullable=True),
    sa.Column('song_rating_count', sa.Integer(), nullable=True),
    sa.Column('total_song_rating', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['album_id'], ['Album.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('audio_file_path'),
    sa.UniqueConstraint('name')
    )
    op.create_table('Playlist_song',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('playlist_id', sa.Integer(), nullable=True),
    sa.Column('song_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['playlist_id'], ['Playlist.id'], ),
    sa.ForeignKeyConstraint(['song_id'], ['Song.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('Playlist_song')
    op.drop_table('Song')
    op.drop_table('User')
    op.drop_table('Playlist')
    op.drop_table('Album')
    # ### end Alembic commands ###
